from customtkinter import*
def change_skin():
    color = None
    screen_1 = CTk()
    screen_1.geometry('600x600')
    red_button = CTkButton(screen_1, 100, 100, fg_color='red', text="", )
    red_button.place(x=10, y = 0)
    blue_button = CTkButton(screen_1, 100, 100, fg_color='blue', text="")
    blue_button.place(x=115, y = 0)
    white_button = CTkButton(screen_1, 100, 100, fg_color='white', text="")
    white_button.place(x=220, y = 0)
    yellow_button = CTkButton(screen_1, 100, 100, fg_color='yellow', text="")
    yellow_button.place(x=325, y = 0)
    black_button = CTkButton(screen_1, 100, 100, fg_color='black', text="")
    black_button.place(x=430, y = 0)
    screen_1.mainloop()
screen = CTk()
screen.title("launcher")
screen.geometry('400x400')
entry_button = CTkButton(screen, 300, 100, text= 'увійти', command=None)
entry_button.place(x =50, y=0)
skin_change_button = CTkButton(screen, 300, 100, text = "змінити колір гравця", command=change_skin)
skin_change_button.place(x = 50, y = 110)
exit_button = CTkButton(screen, 300, 100, text='вийти', command=None)
exit_button.place(x=50, y = 220)
screen.mainloop()